### PR TITLE
refactored/enhanced tracing

### LINKED ISSUE #31: Add traces with different levels
Currently there are 3 macros to trace information `TRACE_LEVELXX` (see `trace.h`). However they are not really used and there is a random mix between normal prints and this macros.

Task:
* Use the different `TRACE_LEVELXX` macros according to the relevancy of what is being traces. Level 0 for important information, level 1 for more detailed stuff and level 2 for very detailed traces.
* Replace the existing prints.

### PR DESCRIPTION
**Pull request by nopeslide**
fixes #31

### CODE REVIEW

**Comment by alrevuelta** [comment]
Looks good, few comments:
* I would "merge" all "normal" and "if" traces. So for example `TRACE_TENSOR` and `TRACE_TENSOR_IF` becomes just one named `TRACE_TENSOR` that is the conditional one. So if we want to always trace if we call it with `TRACE_TENSOR(1)`. Same applies to the other ones, so instead of having 22 tracing functions, we just have 11.
* I understand that `TRACE(1)`, `TRACE(2)` and `TRACE(3)` is equivalent to `TRACE_INFO()`, `TRACE_DETAIL()` and `TRACE_INTERNAL()`? If so, why having `TRACE()` at all? or why having all other three? I saw you changed `TRACE_DEBUG` to `INTERNAL`. TBH I still prefer having `TRACE_1`, `TRACE_2` and `TRACE_3`. The use of info, detail and internal is quite arbitrary to me so thats why I still prefer numbers.
* I'm trying to simplify the tracing because I want people to use them correctly. The more variants and complexity tracing has, the more time people will "waste" trying to understand it. Why complicating it if we can keep it simple.
* Could you add some documentation for it? Both in 01_Documentation.md and 02_Testing.md are ok to me.

**Comment by nopeslide** [comment]
> Looks good, few comments:
> 
>     * I would "merge" all "normal" and "if" traces. So for example `TRACE_TENSOR` and `TRACE_TENSOR_IF` becomes just one named `TRACE_TENSOR` that is the conditional one. So if we want to always trace if we call it with `TRACE_TENSOR(1)`. Same applies to the other ones, so instead of having 22 tracing functions, we just have 11.
> 
>     * I understand that `TRACE(1)`, `TRACE(2)` and `TRACE(3)` is equivalent to `TRACE_INFO()`, `TRACE_DETAIL()` and `TRACE_INTERNAL()`? If so, why having `TRACE()` at all? or why having all other three? I saw you changed `TRACE_DEBUG` to `INTERNAL`. TBH I still prefer having `TRACE_1`, `TRACE_2` and `TRACE_3`. The use of info, detail and internal is quite arbitrary to me so thats why I still prefer numbers.
> 
was mostly testing around, and yeah it doesn't quite achieve what I wanted.
what about I simplify the interface to
```c
TRACE( level, condition, format, var... )
```

>     * Could you add some documentation for it? Either in 01_Documentation.md and 02_Testing.md are ok to me.

will do when the interface doesn't change anymore :D

another thing, I would replace the `TRACE_FILE` and `TRACE_FUNCTION` defines by env variables, so they can be set without recompiling.
so you compile with `TRACE_LEVEL=0` once as default and then can overwrite the actual tracing granularity on each execution.

```bash
make all TRACE_LEVEL=0 #activate tracing, without tracing anything`
CONNXR_TRACE_FILE=inference.c:2 ./build/connxr #run binary with finer trace settings
```

**Comment by alrevuelta** [comment]
> TRACE( level, condition, format, var... )

Looks good. I just wanted to have `TRACE_XX` to enforce having only 3 levels so we don't end up having `TRACE(10)` but I like its simplicity.

> will do when the interface doesn't change anymore :D

another thing, I would replace the TRACE_FILE and TRACE_FUNCTION defines by env variables, so they can be set without recompiling.
so you compile with TRACE_LEVEL=0 once as default and then can overwrite the actual tracing granularity on each execution.

Perfect.

**Comment by nopeslide** [comment]
@alrevuelta right direction?

**Comment by nopeslide** [comment]
@alrevuelta If things look alright here I could merge the other PRs.
One thought I had was to maybe replace the type specific traces (`TRACE_TENSOR` and so on) by inline functions so the normal c typechecker can act upon these, but this can also be an issue for later (function type errors are more readable than macro errors for most people :D).

**Comment by nopeslide** [comment]
@alrevuelta 
A btw, I did not remove the original `trace.{c,h}` files and left the inference and testing files as they are.
I only updated the operators.
should I also refactor the rest?

**Comment by alrevuelta** [comment]
> A btw, I did not remove the original trace.{c,h} files and left the inference and testing files as they are.
I only updated the operators.
should I also refactor the rest?

Feel free to merge it. Inference and testing files will change quite a lot so no need to worry now.

**Pull request merged**
