### PR TITLE
Added uncrustify code formatter

### LINKED ISSUE #12: Code formatting
Since we are adding a lot of autogenerated code and formatting this code is pure pain.
How about we add some kind of code formatter for the whole project?

- `clang-format`
  - simple config
    - common styles
    - hate it or love it approach
  - intended for c++
- `uncrustify`
  - complex config
    - almost every token transition is configurable
    - pain to configure

currently I'm evaluating both for another project and am leaning towards `uncrustify`

### PR DESCRIPTION
**Pull request by nopeslide**
fixes #12 

@alrevuelta 
any suggestions regarding format style is welcome

### CODE REVIEW

**Comment by alrevuelta** [comment]
Is the `cfg` file a standard or custom one? Looks good to me. I will add the format-check to CI soon.

**Comment by nopeslide** [comment]
> Is the `cfg` file a standard or custom one? Looks good to me. I will add the format-check to CI soon.

It's a custom one. the original does almost no formatting (most options are set to ignore).
Btw uncrustify moves fast. I opened a feature request issue (a missing config option) the other day and it was implemented and merged in around 2 days.
Should I add it as `third_party` submodule if we rely on it for formatting the generated code?
It would also make sense to share the uncrustify version if we have a CI check.

**Comment by nopeslide** [comment]
> It would also make sense to share the uncrustify version if we have a CI check.

building it would require `g++`, `cmake` and `python` on a vanilla ubuntu

**Comment by alrevuelta** [comment]
@nopeslide 
It's a custom one. the original does almost no formatting (most options are set to ignore).
Btw uncrustify moves fast. I opened a feature request issue (a missing config option) the other day and it was implemented and merged in around 2 days.
Should I add it as third_party submodule if we rely on it for formatting the generated code?
It would also make sense to share the uncrustify version if we have a CI check.

I would prefer to not add an external dependancy if it is not strictly necessary. Having the same `cfg` file, it should be backwards compatible isn't it?

**Comment by nopeslide** [comment]
> I would prefer to not add an external dependancy if it is not strictly necessary. Having the same `cfg` file, it should be backwards compatible isn't it?

It throws errors on unknown configuration options. I didn't check it, but I assume it still behaves correctly. 
I asked, because integrating a format check into the CI pipeline would make it a development dependency which should be provided, shouldn't it?

**Comment by alrevuelta** [comment]
> I asked, because integrating a format check into the CI pipeline would make it a development dependency which should be provided, shouldn't it?

My idea was to just use `brew install` for macOS and `apt-get` for linux and just get the latest version.

**Pull request closed without merging**
