### PR TITLE
Mobilenetv2 operators

### PR DESCRIPTION
**Pull request by nopeslide**
- based on #34  & #37 
Added an implementation of `clip_12` and `globalaveragepool_1` for the mobilenetv2 network.

### CODE REVIEW

**Comment by alrevuelta** [comment]
Nice. I assume it is [this model](https://github.com/onnx/models/tree/master/vision/classification/mobilenet). Is it working end to end with the [test vectors](https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.tar.gz)? If so would be nice to add both the `onnx` and the test vectors to `test` folders and adding a test case to `include/test/models`.

**Comment by nopeslide** [comment]
> Nice. I assume it is [this model](https://github.com/onnx/models/tree/master/vision/classification/mobilenet). Is it working end to end with the [test vectors](https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.tar.gz)? If so would be nice to add both the `onnx` and the test vectors to `test` folders and adding a test case to `include/test/models`.

Actually it's a custom one, but the onnx one shouldn't be so different.

**Comment by alrevuelta** [comment]
Perfect, once we merge this I can take care of adding the onnx one.

**Comment by alrevuelta** [comment]
@nopeslide Is this ready to merge?

**Comment by nopeslide** [comment]
@alrevuelta yes it is, just updated the operator status

**Pull request merged**
